pyside-uic callhistory_ui.ui > callhistory_ui.py
pyside-uic safbookmarks_ui.ui > safbookmarks_ui.py
pyside-uic whatsapp_ui.ui > whatsapp_ui.py
pyside-uic general_ui.ui > general_ui.py
pyside-uic addressbook_ui.ui > addressbook_ui.py
pyside-uic networkident_ui.ui > networkident_ui.py
pyside-uic safaristate_ui.ui > safaristate_ui.py
pyside-uic thumbsbrowser_ui.ui > thumbsbrowser_ui.py
pyside-uic sms_ui.ui > sms_ui.py
pyside-uic note_ui.ui > note_ui.py